In [1]:
import numpy as np

In [2]:
class NeuralNetwork:
    def __init__(self):
        self.weights=np.array([[0],[0],[0]],dtype="float64")
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    def sigmoid_derivative(self,x):
        return x*(1-x)
    def think(self,inputs):
        inputs=inputs.astype(float)
        outputs=self.sigmoid(np.dot(inputs,self.weights))
        return outputs
    def train(self,training_inputs,training_outputs,iteration):
        outputs=self.think(training_inputs)
        error=training_outputs-outputs
        adjustments=error*self.sigmoid_derivative(outputs)
        self.weights+=np.dot(training_inputs.T,adjustments)

In [3]:
training_inputs=np.array([[0,1,1],[1,0,0],[1,0,1],[0,1,0]])
print(training_inputs)

[[0 1 1]
 [1 0 0]
 [1 0 1]
 [0 1 0]]


In [4]:
training_outputs=np.array([[0,1,1,0]]).T
print(training_outputs)

[[0]
 [1]
 [1]
 [0]]


In [5]:
nn=NeuralNetwork()
nn.train(training_inputs,training_outputs,10000)

In [10]:
#testing
a=int(input("input 1: "))
b=int(input("input 2: "))
c=int(input("input 3: "))
print("output: ",nn.think(np.array([a,b,c]))[0].round())

input 1:  1
input 2:  0
input 3:  0


output:  1.0
