In [21]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv("car_price_dataset.csv")
df.head(5)

,Car_Age,KM_Driven,Fuel_Type,Owner_Type,Mileage,Engine_Size,Price
0,1,12000,Petrol,1,20,1200,720000
1,2,18000,Petrol,1,19,1200,680000
2,3,25000,Diesel,1,22,1500,650000
3,4,30000,Diesel,2,21,1500,620000
4,5,40000,Petrol,2,18,1300,580000


In [6]:
X=df.iloc[:,:6].values
y=df.iloc[:,6].values


In [27]:
#encode dataset using lableencoder
#converting into 0/1
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])


In [28]:
X


array([[1, 2, 1, 1, 20, 1200],
       [2, 8, 1, 1, 19, 1200],
       [3, 16, 0, 1, 22, 1500],
       [4, 24, 0, 2, 21, 1500],
       [5, 32, 1, 2, 18, 1300],
       [6, 40, 0, 2, 20, 1500],
       [7, 48, 0, 3, 19, 1600],
       [8, 56, 1, 2, 17, 1300],
       [9, 64, 0, 3, 18, 1600],
       [10, 72, 1, 3, 16, 1200],
       [1, 7, 1, 1, 21, 1200],
       [2, 11, 0, 1, 22, 1500],
       [3, 19, 1, 1, 19, 1300],
       [4, 29, 0, 2, 21, 1500],
       [5, 35, 1, 2, 18, 1300],
       [6, 43, 0, 2, 20, 1500],
       [7, 53, 0, 3, 19, 1600],
       [8, 59, 1, 2, 17, 1300],
       [9, 67, 0, 3, 18, 1600],
       [10, 75, 1, 3, 16, 1200],
       [1, 0, 1, 1, 21, 1200],
       [2, 9, 0, 1, 22, 1500],
       [3, 17, 1, 1, 19, 1300],
       [4, 25, 0, 2, 21, 1500],
       [5, 33, 1, 2, 18, 1300],
       [6, 41, 0, 2, 20, 1500],
       [7, 49, 0, 3, 19, 1600],
       [8, 57, 1, 2, 17, 1300],
       [9, 65, 0, 3, 18, 1600],
       [10, 73, 1, 3, 16, 1200],
       [1, 5, 1, 1, 20, 1200],
       [2, 

In [29]:
y

array([720000, 680000, 650000, 620000, 580000, 540000, 500000, 470000,
       430000, 400000, 710000, 670000, 640000, 610000, 570000, 530000,
       495000, 460000, 425000, 395000, 725000, 690000, 660000, 630000,
       590000, 550000, 510000, 480000, 440000, 410000, 715000, 675000,
       645000, 615000, 575000, 535000, 505000, 475000, 435000, 405000,
       705000, 665000, 635000, 605000, 565000, 525000, 495000, 465000,
       425000, 395000, 720000, 680000, 650000, 620000, 580000, 540000,
       500000, 470000, 430000, 400000, 718000, 678000, 648000, 618000,
       578000, 538000, 498000, 468000, 428000, 398000, 722000, 682000,
       652000, 622000, 582000, 542000, 502000, 472000, 432000, 402000])

In [30]:
#split data set into taraining and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [31]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.fit_transform(X_test)

In [32]:

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [45]:
y_pred=model.predict(X_test)
y_pred

array([708511.65403916, 463021.12848804, 474420.47356452, 662051.67718384,
       513869.95309941, 521469.51648373, 719910.99911564, 625363.2552961 ,
       415985.35680533, 327263.42237031, 563704.15167214, 565604.04251822,
       612064.01937354, 569403.82421038, 672286.16136904, 476320.3644106 ])

In [46]:
y_test

array([665000, 495000, 510000, 645000, 535000, 538000, 690000, 620000,
       475000, 395000, 565000, 575000, 605000, 582000, 650000, 500000])

In [54]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print("accuracy",r2)

accuracy 0.836464592151831
