# Numpy

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import numpy as np 
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
print(a.ndim)

1


In [4]:
print(b.ndim)

2


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.size)

4


In [7]:
print(a.dtype)

int64


In [12]:
a1=np.zeros((2,3))
print(a1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
a2=np.ones((3,3))
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
a3=np.eye(3)
print(a3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
a4=np.arange(1,10,2)
print(a4)

[1 3 5 7 9]


In [16]:
a5=np.linspace(1,3,3)
print(a5)

[1. 2. 3.]


In [17]:
a6=np.random.rand(3,3)
print(a6)

[[0.99500052 0.91711045 0.93223658]
 [0.88625952 0.04468079 0.22041828]
 [0.56074239 0.33291855 0.94810099]]


In [21]:
arr=np.array([10,20,30,40])
print(arr)
print(arr[3])
print(arr[1:4])

[10 20 30 40]
40
[20 30 40]


In [30]:
mat=([[10,20,30,40],[50,60,70,80]])
print(mat)
print(mat[1:4])


[[10, 20, 30, 40], [50, 60, 70, 80]]
[[50, 60, 70, 80]]


In [35]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a**2)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[1 4 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [42]:
a=np.array([1,2,3,4,5])
print(np.max(a))
print(np.min(a))
print(np.std(a))
print(np.sum(a))
print(np.mean(a))

5
1
1.4142135623730951
15
3.0


In [46]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))
print(np.linalg.det(a))
print(np.linalg.inv(a))


[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
arr=np.array([12,12,13,14,15])
print(np.min(arr))